import { Container } from 'inversify';
import Database from '../configs/database';
import NhanVienService from '../services/nhanvien.service';
import NhanVienRepository from '../repositories/nhanvien.repository';
import PhongBanService from '../services/phongban.service';
import PhongBanRepository from '../repositories/phongban.repository';
import CaLamService from '../services/calam.service';
import CaLamRepository from '../repositories/calam.repository';
import UuTienService from '../services/uutien.service';
import UuTienRepository from '../repositories/uutien.repository';
import VaiTroService from '../services/vaitro.service';
import VaiTroRepository from '../repositories/vaitro.repository';
import NhanVienController from '../controllers/nhanvien.controller';
import PhongBanController from '../controllers/phongban.controller';
import CaLamController from '../controllers/calam.controller';
import UuTienController from '../controllers/uutien.controller';
import VaiTroController from '../controllers/vaitro.controller';
import { TYPES } from './types';
import VanTayRepository from "../repositories/vantay.repository";
import VanTayService from "../services/vantay.service";
import VanTayController from "../controllers/vantay.controller";
import ChamCongRepository from "../repositories/chamcong.repository";
import ChamcongService from "../services/chamcong.service";
import ChamCongController from "../controllers/chamcong.controller";
import LuongRepository from "../repositories/luong.repository";
import LuongService from "../services/luong.service";
import LuongController from "../controllers/luong.controller";
import TaiKhoanRepository from "../repositories/taikhoan.repository";
import TaiKhoanService from "../services/taikhoan.service";
import TaiKhoanController from "../controllers/taikhoan.controller";
import TangCaRepository from "../repositories/tangca.repository";
import TangCaService from "../services/tangca.service";
import TangCaController from "../controllers/tangca.controller";
import NgayNghiRepository from "../repositories/ngaynghi.repository";
import NgayNghiService from "../services/ngaynghi.service";
import NgayNghiController from "../controllers/ngaynghi.controller";
import LoaiTienTruRepository from "../repositories/loaitientru.repository";
import LoaiTienTruService from "../services/loaitientru.service";
import LoaiTienTruController from "../controllers/loaitientru.controller";
import LoaiTienThuongRepository from "../repositories/loaitienthuong.repository";
import LoaiTienThuongService from "../services/loaitienthuong.service";
import LoaiTienThuongController from "../controllers/loaitienthuong.controller";
import LichSuTruRepository from "../repositories/lichsutru.repository";
import LichSuTruService from "../services/lichsutru.service";
import LichSuTruController from "../controllers/lichsutru.controller";
import LichSuThuongRepository from "../repositories/lichsuthuong.repository";
import LichSuThuongService from "../services/lichsuthuong.service";
import LichSuThuongController from "../controllers/lichsuthuong.controller";
import LichSuUuTienRepository from "../repositories/lichsuuutien.repository";
import LichSuUuTienService from "../services/lichsuuutien.service";
import LichSuUuTienController from "../controllers/lichsuuutien.controller";
import NgayLeRepository from "../repositories/ngayle.repository";
import NgayLeService from "../services/ngayle.service";
import NgayLeController from "../controllers/ngayle.controller";
import EmployeeServiceClient from "../rpc/employee.client";
import DeviceConnectorClient from "../rpc/device.client";
import DeviceController from "../controllers/device.controller";
import NgayPhepRepository from "../repositories/ngayphep.repository";
import NgayPhepService from "../services/ngayphep.service";
import NgayPhepController from '../controllers/ngayphep.controller';
import HeThongRepository from "../repositories/hethong.repository";
import HeThongService from "../services/hethong.service";
import HeThongController from "../controllers/hethong.controller";
import CaLamTrongTuanRepository from "../repositories/calam.trongtuan.repository";
import CaLamTrongTuanService from "../services/calam.trongtuan.service";
import CaLamTrongTuanController from "../controllers/calam.trongtuan.controller";
import PhucapRepository from "../repositories/phucap.repository";
import PhucapService from "../services/phucap.service";
import PhuCapController from "../controllers/phucap.controller";
import ThemPhuCapController from "../controllers/themphucap.controller";
import ThemPhuCapService from "../services/themphucap.service";
import ThemPhuCapRepository from "../repositories/themphucap.repository";
import QuyenHanRepository from "../repositories/quyenhan.repository";
import QuyenHanService from "../services/quyenhan.service";
import QuyenHanController from "../controllers/quyenhan.controller";
import EmailService from "../services/email.service";

const container = new Container();

// Database
container.bind<Database>(TYPES.Database).to(Database).inSingletonScope();

// Repositories
container.bind<NhanVienRepository>(TYPES.NhanVienRepository).to(NhanVienRepository);
container.bind<PhongBanRepository>(TYPES.PhongBanRepository).to(PhongBanRepository);
container.bind<CaLamRepository>(TYPES.CaLamRepository).to(CaLamRepository);
container.bind<UuTienRepository>(TYPES.UuTienRepository).to(UuTienRepository);
container.bind<VaiTroRepository>(TYPES.VaiTroRepository).to(VaiTroRepository);
container.bind<VanTayRepository>(TYPES.VanTayRepository).to(VanTayRepository);
container.bind<ChamCongRepository>(TYPES.ChamCongRepository).to(ChamCongRepository);
container.bind<LuongRepository>(TYPES.LuongRepository).to(LuongRepository);
container.bind<TaiKhoanRepository>(TYPES.TaiKhoanRepository).to(TaiKhoanRepository);
container.bind<TangCaRepository>(TYPES.TangCaRepository).to(TangCaRepository);
container.bind<NgayNghiRepository>(TYPES.NgayNghiRepository).to(NgayNghiRepository);
container.bind<LoaiTienTruRepository>(TYPES.LoaiTienTruRepository).to(LoaiTienTruRepository);
container.bind<LoaiTienThuongRepository>(TYPES.LoaiTienThuongRepository).to(LoaiTienThuongRepository);
container.bind<LichSuTruRepository>(TYPES.LichSuTruRepository).to(LichSuTruRepository);
container.bind<LichSuThuongRepository>(TYPES.LichSuThuongRepository).to(LichSuThuongRepository);
container.bind<LichSuUuTienRepository>(TYPES.LichSuUuTienRepository).to(LichSuUuTienRepository);
container.bind<NgayLeRepository>(TYPES.NgayLeRepository).to(NgayLeRepository);
container.bind<NgayPhepRepository>(TYPES.NgayPhepRepository).to(NgayPhepRepository);
container.bind<HeThongRepository>(TYPES.HeThongRepository).to(HeThongRepository);
container.bind<CaLamTrongTuanRepository>(TYPES.CaLamTrongTuanRepository).to(CaLamTrongTuanRepository);
container.bind<PhucapRepository>(TYPES.PhuCapRepository).to(PhucapRepository);
container.bind<ThemPhuCapRepository>(TYPES.ThemPhuCapRepository).to(ThemPhuCapRepository);
container.bind<QuyenHanRepository>(TYPES.QuyenHanRepository).to(QuyenHanRepository);
// Services
container.bind<NhanVienService>(TYPES.NhanVienService).to(NhanVienService);
container.bind<PhongBanService>(TYPES.PhongBanService).to(PhongBanService);
container.bind<CaLamService>(TYPES.CaLamService).to(CaLamService);
container.bind<UuTienService>(TYPES.UuTienService).to(UuTienService);
container.bind<VaiTroService>(TYPES.VaiTroService).to(VaiTroService);
container.bind<VanTayService>(TYPES.VanTayService).to(VanTayService);
container.bind<ChamcongService>(TYPES.ChamCongService).to(ChamcongService);
container.bind<LuongService>(TYPES.LuongService).to(LuongService);
container.bind<TaiKhoanService>(TYPES.TaiKhoanService).to(TaiKhoanService);
container.bind<TangCaService>(TYPES.TangCaService).to(TangCaService);
container.bind<NgayNghiService>(TYPES.NgayNghiService).to(NgayNghiService);
container.bind<LoaiTienTruService>(TYPES.LoaiTienTruService).to(LoaiTienTruService);
container.bind<LoaiTienThuongService>(TYPES.LoaiTienThuongService).to(LoaiTienThuongService);
container.bind<LichSuTruService>(TYPES.LichSuTruService).to(LichSuTruService);
container.bind<LichSuThuongService>(TYPES.LichSuThuongService).to(LichSuThuongService);
container.bind<LichSuUuTienService>(TYPES.LichSuUuTienService).to(LichSuUuTienService);
container.bind<NgayLeService>(TYPES.NgayLeService).to(NgayLeService);
container.bind<NgayPhepService>(TYPES.NgayPhepService).to(NgayPhepService);
container.bind<HeThongService>(TYPES.HeThongService).to(HeThongService);
container.bind<CaLamTrongTuanService>(TYPES.CaLamTrongTuanService).to(CaLamTrongTuanService);
container.bind<PhucapService>(TYPES.PhuCapService).to(PhucapService);
container.bind<ThemPhuCapService>(TYPES.ThemPhuCapService).to(ThemPhuCapService);
container.bind<QuyenHanService>(TYPES.QuyenHanService).to(QuyenHanService);
container.bind<EmailService>(TYPES.EmailService).to(EmailService);
// Controllers
container.bind<NhanVienController>(TYPES.NhanVienController).to(NhanVienController);
container.bind<PhongBanController>(TYPES.PhongBanController).to(PhongBanController);
container.bind<CaLamController>(TYPES.CaLamController).to(CaLamController);
container.bind<UuTienController>(TYPES.UuTienController).to(UuTienController);
container.bind<VaiTroController>(TYPES.VaiTroController).to(VaiTroController);
container.bind<VanTayController>(TYPES.VanTayController).to(VanTayController);
container.bind<ChamCongController>(TYPES.ChamCongController).to(ChamCongController);
container.bind<LuongController>(TYPES.LuongController).to(LuongController);
container.bind<TaiKhoanController>(TYPES.TaiKhoanController).to(TaiKhoanController);
container.bind<TangCaController>(TYPES.TangCaController).to(TangCaController);
container.bind<NgayNghiController>(TYPES.NgayNghiController).to(NgayNghiController);
container.bind<LoaiTienTruController>(TYPES.LoaiTienTruController).to(LoaiTienTruController);
container.bind<LoaiTienThuongController>(TYPES.LoaiTienThuongController).to(LoaiTienThuongController);
container.bind<LichSuTruController>(TYPES.LichSuTruController).to(LichSuTruController);
container.bind<LichSuThuongController>(TYPES.LichSuThuongController).to(LichSuThuongController);
container.bind<LichSuUuTienController>(TYPES.LichSuUuTienController).to(LichSuUuTienController);
container.bind<NgayLeController>(TYPES.NgayLeController).to(NgayLeController);
container.bind<DeviceController>(TYPES.DeviceController).to(DeviceController);
container.bind<NgayPhepController>(TYPES.NgayPhepController).to(NgayPhepController);
container.bind<HeThongController>(TYPES.HeThongController).to(HeThongController);
container.bind<CaLamTrongTuanController>(TYPES.CaLamTrongTuanController).to(CaLamTrongTuanController);
container.bind<PhuCapController>(TYPES.PhuCapController).to(PhuCapController);
container.bind<ThemPhuCapController>(TYPES.ThemPhuCapController).to(ThemPhuCapController);
container.bind<QuyenHanController>(TYPES.QuyenHanController).to(QuyenHanController);
//RPC
container.bind<EmployeeServiceClient>(TYPES.EmployeeServiceClient).to(EmployeeServiceClient);
container.bind<DeviceConnectorClient>(TYPES.DeviceConnectorClient).to(DeviceConnectorClient);

export { container };
